### ISSUE TITLE
Error when generating headers with only "all". (after v1.7.6)

### ISSUE THREAD

**Issue by tanopanta** [swaggo/swag#1065]
**Describe the bug**
An error will occur when generating headers with only "all" after v1.7.6. 

**To Reproduce**
generate from

```go
// @Success      200              {string}  string    "ok"
// @failure      400              {string}  string    "error"
// @Header       all              {string}  Token     "token"
```

occured error

```
> swag init
2021/11/29 23:40:17 Generate swagger docs....
2021/11/29 23:40:17 Generate general API Info, search dir:./
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/swaggo/swag.(*Operation).ParseResponseHeaderComment(0xc0000fd9e0, 0xc00002cb91, 0x2c, 0xc0000a2700, 0x5, 0x3b)
        /hoge/go/pkg/mod/github.com/swaggo/swag@v1.7.6/operation.go:897 +0x337
github.com/swaggo/swag.(*Operation).ParseComment(0xc0000fd9e0, 0xc00002cb80, 0x3d, 0xc0000a2700, 0x0, 0x0)
        /hoge/go/pkg/mod/github.com/swaggo/swag@v1.7.6/operation.go:120 +0x398
github.com/swaggo/swag.(*Parser).ParseRouterAPIInfo(0xc000119520, 0xc00002e420, 0x21, 0xc0000a2700, 0xc00000eae0, 0x8e3300)
        /hoge/go/pkg/mod/github.com/swaggo/swag@v1.7.6/parser.go:695 +0x1a7
github.com/swaggo/swag.(*PackagesDefinitions).RangeFiles(0xc00000e918, 0xc0000cd968, 0x0, 0x0)
        /hoge/go/pkg/mod/github.com/swaggo/swag@v1.7.6/packages.go:88 +0x270
github.com/swaggo/swag.(*Parser).ParseAPIMultiSearchDir(0xc000119520, 0xc000111c70, 0x1, 0x1, 0x997e1f, 0x7, 0x64, 0x1, 0x1)
        /hoge/go/pkg/mod/github.com/swaggo/swag@v1.7.6/parser.go:288 +0x345
github.com/swaggo/swag/gen.(*Gen).Build(0xc000111ba0, 0xc0000cdc58, 0x0, 0x0)
        /hoge/go/pkg/mod/github.com/swaggo/swag@v1.7.6/gen/gen.go:106 +0x37d
main.initAction(0xc00013e800, 0xe, 0x1a)
        /hoge/go/pkg/mod/github.com/swaggo/swag@v1.7.6/cmd/swag/main.go:110 +0x4a9
github.com/urfave/cli/v2.(*Command).Run(0xc0000fd560, 0xc00013e240, 0x0, 0x0)
        /hoge/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc000130680, 0xa3c550, 0xc0000240d0, 0xc000020040, 0x2, 0x2, 0x0, 0x0)
        /hoge/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
        /hoge/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /hoge/go/pkg/mod/github.com/swaggo/swag@v1.7.6/cmd/swag/main.go:174 +0x4f5
```

**Expected behavior**

I want to use only header generation with "all" without defining the header for each status code.

**Your swag version**
1.7.6 (It worked in 1.7.4)

**Your go version**
1.16.2

**Comment by ubogdan** [comment]
I apologize for this breaking change. The code coverage didn't catch this :(
