### ISSUE TITLE
swag init panic by invalid memory address when used @header 

### ISSUE THREAD

**Issue by lixd** [swaggo/swag#1092]
**Describe the bug**
do swag init panic by invalid memory address when used @header .
i copy some comment  form `readme.md` for test,like this:

```go
// @Header       200              {string}  Location  "/entity/1"
// @Header       200,400,default  {string}  Token     "token"
// @Header       all              {string}  Token2    "token2"
```

and do swag init  and panic like this:

```c
swag init -g cmd/api/api.go -o cmd/api/docs
2021/12/27 12:46:50 Generate swagger docs....
2021/12/27 12:46:50 Generate general API Info, search dir:./
2021/12/27 12:46:51 warning: failed to get package name in dir: ./, error: execute go list command, exit status 1, stdout:, stderr:no Go files in /mnt/d/wlinno/projetctss/puug-api
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x818559] 

goroutine 1 [running]:
github.com/swaggo/swag.(*Operation).ParseResponseHeaderComment(0xc000fc8900, {0xc00017fe11, 0x30}, 0xc000ed6c58)
        /home/lixd/go/pkg/mod/github.com/swaggo/swag@v1.7.6/operation.go:884 +0x139
github.com/swaggo/swag.(*Operation).ParseComment(0xc000fc8900, {0xc00017fe00, 0x1}, 0x7)
        /home/lixd/go/pkg/mod/github.com/swaggo/swag@v1.7.6/operation.go:120 +0x287
github.com/swaggo/swag.(*Parser).ParseRouterAPIInfo(0xc00019b1e0, {0xc00017fea0, 0x45}, 0xc000511980)
        /home/lixd/go/pkg/mod/github.com/swaggo/swag@v1.7.6/parser.go:695 +0x1b9
github.com/swaggo/swag.(*PackagesDefinitions).RangeFiles(0xc00000e960, 0xc000813918)
        /home/lixd/go/pkg/mod/github.com/swaggo/swag@v1.7.6/packages.go:88 +0x1ff
github.com/swaggo/swag.(*Parser).ParseAPIMultiSearchDir(0xc00019b1e0, {0xc000193d20, 0x1, 0xc000058100}, {0x7ffc09ea01cc, 0xe}, 0x64)
        /home/lixd/go/pkg/mod/github.com/swaggo/swag@v1.7.6/parser.go:288 +0x325
github.com/swaggo/swag/gen.(*Gen).Build(0xc000193c50, 0xc000813c30)
        /home/lixd/go/pkg/mod/github.com/swaggo/swag@v1.7.6/gen/gen.go:106 +0x2b0
main.initAction(0xc0001b64e0)
        /home/lixd/go/pkg/mod/github.com/swaggo/swag@v1.7.6/cmd/swag/main.go:110 +0x39a
github.com/urfave/cli/v2.(*Command).Run(0xc00013f560, 0xc0001be380)
        /home/lixd/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
github.com/urfave/cli/v2.(*App).RunContext(0xc0001b6340, {0x9b5750, 0xc0000240c8}, {0xc0000201e0, 0x6, 0x6})
        /home/lixd/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
github.com/urfave/cli/v2.(*App).Run(...)
        /home/lixd/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /home/lixd/go/pkg/mod/github.com/swaggo/swag@v1.7.6/cmd/swag/main.go:174 +0x55d

```

**To Reproduce**

1. Update To swag version v1.7.6 and  go version go1.17.5
2. add @header comment onto controller
3. swag init

**Expected behavior**
init success.

**Screenshots**

**Your swag version**
swag version v1.7.6

**Your go version**
go version go1.17.5 linux/amd64

**Desktop (please complete the following information):**

 - OS: [Ubuntu20.04 by Windows11 WSL2]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

Windows10 has the same question。

**Comment by ubogdan** [comment]
We know the issue and it was fixed in 1.7.8. Please test with the latest version and let us know.

Happy holidays.
