### ISSUE TITLE
Support for user type define

### ISSUE THREAD

**Issue by zhongkeqin** [swaggo/swag#122]
Problems I encountered:
1. In the celler example, change the Account model to:
```go
type AccountId int

type Account struct {
	ID   AccountId       `json:"id" example:"1" format:"int64"`    // doesn't work
	Name string    `json:"name" example:"account name"`
	UUID uuid.UUID `json:"uuid" example:"550e8400-e29b-41d4-a716-446655440000" format:"uuid"`
}
```

2. Execute "swag init" :
```
2018/05/15 16:24:59 Generate swagger docs....
2018/05/15 16:24:59 Generate general API Info
2018/05/15 16:24:59 Generating model.Admin
panic: AccountId is unsupported type in example value

goroutine 1 [running]:
github.com/swaggo/swag.defineTypeOfExample(0xc420465d50, 0x9, 0xc42001c823, 0x1, 0xc42001c823, 0x1)
	/Users/mulan/goget/src/github.com/swaggo/swag/parser.go:633 +0xc4a
github.com/swaggo/swag.(*Parser).parseField(0xc4201403f0, 0xc420200240, 0x0)
	/Users/mulan/goget/src/github.com/swaggo/swag/parser.go:557 +0x460
github.com/swaggo/swag.(*Parser).parseStruct(0xc4201403f0, 0xc4203cf039, 0x5, 0xc420200240, 0x0)
	/Users/mulan/goget/src/github.com/swaggo/swag/parser.go:438 +0x61
github.com/swaggo/swag.(*Parser).parseTypeSpec(0xc4201403f0, 0xc4203cf039, 0x5, 0xc420487e30, 0xc420140600)
	/Users/mulan/goget/src/github.com/swaggo/swag/parser.go:410 +0x24d
github.com/swaggo/swag.(*Parser).ParseDefinition(0xc4201403f0, 0xc4203cf039, 0x5, 0xc420487e30, 0xc420460457, 0x7)
	/Users/mulan/goget/src/github.com/swaggo/swag/parser.go:373 +0x1ac
github.com/swaggo/swag.(*Parser).parseStruct(0xc4201403f0, 0xc4203cf039, 0x5, 0xc4202016c0, 0xc420140450)
	/Users/mulan/goget/src/github.com/swaggo/swag/parser.go:445 +0xd91
github.com/swaggo/swag.(*Parser).parseTypeSpec(0xc4201403f0, 0xc4203cf039, 0x5, 0xc42041f4a0, 0xc4201402a0)
	/Users/mulan/goget/src/github.com/swaggo/swag/parser.go:410 +0x24d
github.com/swaggo/swag.(*Parser).ParseDefinition(0xc4201403f0, 0xc4203cf039, 0x5, 0xc42041f4a0, 0xc420460430, 0x6)
	/Users/mulan/goget/src/github.com/swaggo/swag/parser.go:373 +0x1ac
github.com/swaggo/swag.(*Parser).ParseDefinitions(0xc4201403f0)
	/Users/mulan/goget/src/github.com/swaggo/swag/parser.go:337 +0xbd
github.com/swaggo/swag.(*Parser).ParseAPI(0xc4201403f0, 0x140f157, 0x2, 0x1410186, 0x7)
	/Users/mulan/goget/src/github.com/swaggo/swag/parser.go:77 +0x247
github.com/swaggo/swag/gen.(*Gen).Build(0xc4204b39b8, 0x140f157, 0x2, 0x1410186, 0x7, 0x1411fef, 0xe, 0x0, 0x0, 0x0, ...)
	/Users/mulan/goget/src/github.com/swaggo/swag/gen/gen.go:29 +0x2b1
main.main.func1(0xc420098160, 0xc420070300, 0xc420098160)
	/Users/mulan/goget/src/github.com/zhongkeqin/swag/cmd/swag/main.go:24 +0x173
github.com/urfave/cli.HandleAction(0x138aa20, 0x14282f8, 0xc420098160, 0x0, 0xc420070360)
	/Users/mulan/goget/src/github.com/urfave/cli/app.go:501 +0xc8
github.com/urfave/cli.Command.Run(0x140f6e3, 0x4, 0x0, 0x0, 0xc420144020, 0x1, 0x1, 0x141206d, 0xe, 0x0, ...)
	/Users/mulan/goget/src/github.com/urfave/cli/command.go:165 +0x47d
github.com/urfave/cli.(*App).Run(0xc4201b8000, 0xc42000c080, 0x2, 0x2, 0x0, 0x0)
	/Users/mulan/goget/src/github.com/urfave/cli/app.go:259 +0x6e8
```

**Comment by pei0804** [comment]
relate #109  
Because it is a duplicate it closes
