### ISSUE TITLE
Panic on generation

### ISSUE THREAD

**Issue by farexw** [swaggo/swag#1368]
**Describe the bug**
Panic on generation
panic: runtime error: invalid memory address or nil pointer dereference

**To Reproduce**
Package structure:   
```
.
.
├── api
│   └── swagger
│       └── v3
│           └── docs.go
├── go.mod
├── go.sum
├── internal
│   └── server
│       ├── handlers
│       │   ├── v3
│       │   │   ├── apps
│       │   │   │   ├── handler.go
│       │   │   ├── products
│       │   │   │   ├── handler.go
│       │   │   └── swagger.go

```

swagger.go
```
//go:generate swag init --dir . --parseDependency --parseInternal -g swagger.go --output ../../../../api/swagger/v3

// @Title                                       Some Title API
// @Version                                  1.0.0
// @BasePath                               /v3
// @host                                       localhost:8080
// @Schemes                               https http
// @securityDefinitions.apikey  ApiKeyAuth
// @in                                           header
// @name                                    Authorization
// @description                           Description for what is this security definition being used
```

**Expected behavior**
```
/usr/local/go/bin/go generate -run swag init --dir . --parseDependency --parseInternal -g swagger.go --output ../../../../api/swagger/v3
2022/10/27 14:02:12 Generate swagger docs....
2022/10/27 14:02:12 Generate general API Info, search dir:.
2022/10/27 14:02:27 Generating request.AppRegisterV3RequestDto
2022/10/27 14:02:44 Generating response.AppRegisterV3Response
2022/10/27 14:02:45 Generating errhub.ErrorResponse
2022/10/27 14:02:45 Generating request.AppUpdateV3RequestDto
2022/10/27 14:02:45 Generating response.AppUpdateV3Response
2022/10/27 14:02:45 Generating response.SetIconsV3Response
2022/10/27 14:02:45 Generating request.RoutesSetV3RequestDto
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x100c61b44]

goroutine 1 [running]:
github.com/swaggo/swag.(*PackagesDefinitions).FindTypeSpec(0x140001a8810, {0x1400062e210, 0x6}, 0x14000646080, 0x1)
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/packages.go:321 +0x404
github.com/swaggo/swag.(*Parser).getTypeSchema(0x1400024d860, {0x1400062e210, 0x6}, 0x20?, 0x1)
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/parser.go:807 +0x930
github.com/swaggo/swag.(*Parser).parseStructField(0x1400024d860, 0x9?, 0x140006427c0)
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/parser.go:1179 +0x398
github.com/swaggo/swag.(*Parser).parseStruct(0x3c?, 0x1401e891380?, 0x1400063a510)
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/parser.go:1094 +0xc4
github.com/swaggo/swag.(*Parser).parseTypeExpr(0x1400024d860, 0x100c8c48d?, {0x100e2c6f8?, 0x1400063c300?}, 0xb8?)
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/parser.go:1045 +0x3a8
github.com/swaggo/swag.(*Parser).ParseDefinition(0x1400024d860, 0x14018c6eec0)
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/parser.go:952 +0x434
github.com/swaggo/swag.(*Parser).getTypeSchema(0x1400024d860, {0x140003143de, 0x1d}, 0x101124ee8?, 0x1)
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/parser.go:833 +0xce8
github.com/swaggo/swag.(*Operation).parseObjectSchema(0x1401f64f9e0, {0x140003143de, 0x1d}, 0x100c58898?)
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/operation.go:760 +0x1060
github.com/swaggo/swag.(*Operation).parseAPIObjectSchema(0x140003143fc?, {0x100c877e4, 0x6}, {0x140003143de?, 0x9?}, 0x100c87a54?)
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/operation.go:830 +0x23c
github.com/swaggo/swag.(*Operation).ParseParamComment(0x1401f64f9e0, {0x140003143d0, 0x45}, 0x100c997ba?)
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/operation.go:338 +0xda8
github.com/swaggo/swag.(*Operation).ParseComment(0x1401f64f9e0, {0x140003143c0?, 0x1?}, 0x1b?)
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/operation.go:122 +0x1a8
github.com/swaggo/swag.(*Parser).ParseRouterAPIInfo(0x1400024d860, {0x14000314720, 0x5a}, 0x14000323300)
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/parser.go:726 +0x154
github.com/swaggo/swag.rangeFiles(0x140002539b0, 0x140065c7968)
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/packages.go:88 +0x1cc
github.com/swaggo/swag.(*Parser).ParseAPIMultiSearchDir(0x1400024d860, {0x14000243f50?, 0x1?, 0x1400019a0f0?}, {0x16f58f7cf?, 0xa?}, 0x64)
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/parser.go:319 +0x274
github.com/swaggo/swag/gen.(*Gen).Build(0x140001cf460, 0x1400028c000)
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/gen/gen.go:155 +0x398
main.initAction(0x140002623c0?)
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/cmd/swag/main.go:129 +0x448
github.com/urfave/cli/v2.(*Command).Run(0x140002237a0, 0x1400026c440)
	/Users/evgenijgusev/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x50c
github.com/urfave/cli/v2.(*App).RunContext(0x14000244ea0, {0x100e2ce20?, 0x140001b4008}, {0x140001b8000, 0xa, 0xa})
	/Users/evgenijgusev/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x888
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/evgenijgusev/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/Users/evgenijgusev/go/pkg/mod/github.com/swaggo/swag@v1.8.0/cmd/swag/main.go:195 +0x660
swagger.go:7: running "swag": exit status 2

Process finished with exit code 1
```

**Your swag version**
swag version v1.8.4
swag version v1.8.7

**Your go version**
go version go1.18.4 darwin/arm64

**Desktop (please complete the following information):**
ProductName:		macOS
ProductVersion:		13.0
BuildVersion:		22A380

Please tell me how to solve this problem?

**Comment by sdghchj** [comment]
debug it
