### ISSUE TITLE
Generics Issue: Panic when multiple nested generics used.

### ISSUE THREAD

**Issue by gaborpongracz** [swaggo/swag#1434]
**Describe the bug**
`swag init` panics when try to process the struct with multi-level nested generics.
<details>
              <summary>The error message</summary>

      
      panic: interface conversion: interface {} is *ast.Field, not *ast.TypeSpec
      
      goroutine 1 [running]:
      github.com/swaggo/swag.getExtendedGenericFieldType(0x13?, {0x104c956f0?, 0x14009471b20?}, 0x104aa3700?)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/generics.go:237 +0x1f0
      github.com/swaggo/swag.getGenericFieldType(0x14009472380, {0x104c957b0?, 0x1400946b2c0}, 0x0?)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/generics.go:274 +0x90
      github.com/swaggo/swag.getFieldType(0x0?, {0x104c957b0?, 0x1400946b2c0?})
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/parser.go:1399 +0x168
      github.com/swaggo/swag.getExtendedGenericFieldType(0x14009ecfda8?, {0x104c957b0?, 0x1400946b2c0?}, 0x1400d90cf30?)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/generics.go:242 +0x1d4
      github.com/swaggo/swag.getGenericFieldType(0x14009472380, {0x104c957b0?, 0x1400946b2f0}, 0x1046f08a0?)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/generics.go:274 +0x90
      github.com/swaggo/swag.(*PackagesDefinitions).resolveGenericType(0x104c17600?, 0x0?, {0x104c957b0?, 0x1400946b2f0?}, 0x1400d4f9cd9?)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/generics.go:185 +0x16c
      github.com/swaggo/swag.(*PackagesDefinitions).resolveGenericType(0x104c11e20?, 0x140001b1ad0?, {0x104c95a50?, 0x1400944adc8?}, 0x104ada2b3?)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/generics.go:209 +0x528
      github.com/swaggo/swag.(*PackagesDefinitions).parametrizeGenericType(0x140001b1b00, 0x1400d90cea0?, 0x1400c902be0, {0x1400d4f9cc1?, 0x0?})
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/generics.go:104 +0x5d8
      github.com/swaggo/swag.(*PackagesDefinitions).FindTypeSpec(0x140001b1b00, {0x1400d4f9cc1, 0x1e}, 0x14009472380)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/packages.go:552 +0x3f8
      github.com/swaggo/swag.(*Parser).getTypeSchema(0x140001a4b60, {0x1400d4f9cc1, 0x1e}, 0xd?, 0x1)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/parser.go:998 +0x864
      github.com/swaggo/swag.(*Parser).parseStructField(0x140001a4b60, 0x1400d9717d0?, 0x1400947c2c0)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/parser.go:1350 +0x364
      github.com/swaggo/swag.(*Parser).parseStruct(0x3f?, 0x1400af0a300?, 0x1400946b200)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/parser.go:1263 +0xc0
      github.com/swaggo/swag.(*Parser).parseTypeExpr(0x140001d40a0?, 0x104ae15bb?, {0x104c95a50?, 0x1400944ad98?}, 0x0?)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/parser.go:1216 +0x1ac
      github.com/swaggo/swag.(*Parser).ParseDefinition(0x140001a4b60, 0x1400c902b90)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/parser.go:1102 +0x3d8
      github.com/swaggo/swag.(*Parser).getTypeSchema(0x140001a4b60, {0x1400013a19b, 0x20}, 0x1400d916c30?, 0x1)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/parser.go:1027 +0xbe4
      github.com/swaggo/swag.parseObjectSchema(0x140001a4b60, {0x1400013a19b, 0x20}, 0x2800000000000000?)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/operation.go:838 +0x1118
      github.com/swaggo/swag.(*Operation).parseObjectSchema(...)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/operation.go:792
      github.com/swaggo/swag.(*Operation).parseAPIObjectSchema(0x14000000a20, {0x1400013a18d, 0x2e}, {0x1400013a193, 0x6}, {0x1400013a19b, 0x20}, 0x1400d4fdf30?)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/operation.go:918 +0x3b8
      github.com/swaggo/swag.(*Operation).ParseResponseComment(0x14000000a20, {0x1400013a18d, 0x2e}, 0x2?)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/operation.go:950 +0x118
      github.com/swaggo/swag.(*Operation).ParseComment(0x14000000a20, {0x1400013a180?, 0x1?}, 0x100000000000000?)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/operation.go:143 +0x3ec
      github.com/swaggo/swag.(*Parser).ParseRouterAPIInfo(0x140001a4b60, 0x1400012ca00)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/parser.go:895 +0x1a8
      github.com/swaggo/swag.(*PackagesDefinitions).RangeFiles(0x140001b1b00, 0x14009ed1878)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/packages.go:107 +0x288
      github.com/swaggo/swag.(*Parser).ParseAPIMultiSearchDir(0x140001a4b60, {0x14000077840?, 0x2?, 0x0?}, {0x16b75b892?, 0xd?}, 0x64)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/parser.go:405 +0x2fc
      github.com/swaggo/swag/gen.(*Gen).Build(0x140001b1950, 0x140001e4000)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/gen/gen.go:186 +0x508
      main.initAction(0x140001cec80?)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/cmd/swag/main.go:164 +0x6dc
      github.com/urfave/cli/v2.(*Command).Run(0x14000000fc0, 0x140001d0340)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4fc
      github.com/urfave/cli/v2.(*App).RunContext(0x140000a5520, {0x104c96370?, 0x140000280c0}, {0x14000020750, 0xd, 0xd})
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x860
      github.com/urfave/cli/v2.(*App).Run(...)
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
      main.main()
              /Users/gabor.pongracz/REPO/pkg/mod/github.com/swaggo/swag@v1.8.10-0.20221229014139-f916213f4307/cmd/swag/main.go:236 +0x65c
      ```
</details>


**To Reproduce**
Steps to reproduce the behavior:

1. Setup
**Entities:**
```go
package web

import (
	"encoding/json"
)

type TestResponse struct {
	Field1 Entity[int64]   `json:"field_1"`
	Field2 Entity[float64] `json:"field_2"`
}

type Entity[T int64 | float64] struct {
	LineWithFixType     EmptyArray[DataPoint[float64]] `json:"line_with_fix_type"`
	LineWithGenericType EmptyArray[DataPoint[T]]       `json:"line_with_generic_type"`
	MultipleLines       MultipleLines[T]               `json:"multiple_lines"`
}

type DataPoint[T int64 | float64] struct {
	Value     T     `json:"value"`
	Timestamp int64 `json:"timestamp"`
}

// EmptyArray will show [] instead of nil.
type EmptyArray[T any] []T

func (arr EmptyArray[T]) MarshalJSON() ([]byte, error) {
	if arr != nil {
		return json.Marshal([]T(arr))
	}

	return json.Marshal(make([]T, 0))
}

type MultipleLines[T int64 | float64] []NamedLineData[T]

type NamedLineData[T int64 | float64] struct {
	Name string                   `json:"name"`
	Data EmptyArray[DataPoint[T]] `json:"data"`
}
```

**API:**
```go
package api

import (
	"net/http"
)

// GetPosts
// @Summary Test Generics with multi level nesting
// @Description Test one of the edge cases found in generics
// @Accept  json
// @Produce  json
// @Success 200 {object} web.TestResponse
// @Router /use-struct-and-generics-with-multi-level-nesting [get]
func GetPosts(w http.ResponseWriter, r *http.Request) {

}
```
2. Run `swag init`

**Expected behavior**
Generic type should have been parsed correctly, swagger file generated.

**Your swag version**
[Latest master](https://github.com/swaggo/swag/commit/f916213f43077caa4d318efb622b551cf2e45a5c)

**Your go version**
go version go1.19.1 darwin/arm64

**Desktop (please complete the following information):**
 - Chipset: Apple M1 Pro
 - OS: MacOS Ventura 13.1

**Comment by gaborpongracz** [comment]
I've also created a PR could fix this issue, but I have no chance to test in different setups (older go versions, etc...)
Please, check this out and let me know if this is the good solution or just a workaround.
https://github.com/swaggo/swag/pull/1435

**Comment by gaborpongracz** [comment]
@sdghchj Thank you!
