### ISSUE TITLE
Generate Boolean info causes no error, but fails.

### ISSUE THREAD

**Issue by writch** [swaggo/swag#1481]
**Describe the bug**
The first boolean I tried to document gave no error but resulted in the entire Parameters block being replaced.  

In version 1.8.7, the block was replaced with a message that said _Could not render n, see the console_.  

Upgrading to 1.8.10 changed that to _Could not render Dt, see the console._ 

Below is the block of comments which is being processed.  The lines marked _Quarantine_ are the offending lines.  Uncommenting the 'string' version results in all parameters being presented, although the Quarantine is wrong.   It's uncommenting the boolean version which results in failure.

```// @Router      /v1/inventory/room  [post]
// @Tags        Inventory
// @Summary     Add a new Room to the Inventory Rooms
// @Description Add a room with an ID, a name, and a quarantine status
// @Accept      json
// @Produce     json
// @Param       InventoryRoomID     body     string true  "ID of the room to be added"
// @Param       InventoryRoomName   body     string true  "Name of the room to be added"
// @Param       LocationLicense 	body     string true  "The license number of the location making the request."
// //@Param       Quarantine 			body     string false "Quarantine room or not"
// @Param       Quarantine 			body     boolean  false "Quarantine room or not"
// @Success     200             	{object} forms.InventoryRoomResponse  "ok"
// @Failure     400             	{object} api_error.APIError     "Bad Request"```

**To Reproduce**
Steps to reproduce the behavior:
run `swag init` with this set of documentation comments

**Expected behavior**
I expected a parameter named Quarantine to show up in the generated docs as a boolean

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Your swag version**
1.8.10


**Your go version**
1.19

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version:  110.0.1587.57 (Official build) (64-bit)

**Additional context**
Incidentally, changing from 1.8.7 to 1.8.10 also generated errors on other docs unrelated to this issue, but which might be of interest.  

There were two:
vendor/github.com/pelletier/go-toml/v2/internal/characters/utf8.go:183:2, strconv.ParseUint: parsing "b10000000": invalid syntax
and
vendor/github.com/pelletier/go-toml/v2/internal/characters/utf8.go:184:2, strconv.ParseUint: parsing "b10111111": invalid syntax

**Comment by writch** [comment]
I should add that I'm guessing that the _Console_ mentioned is the JavaScript console,   Here's what's in there in red:

```react-dom.production.min.js:216 
        
       Error: Expected `string` for value, got `true`
    at t (index.js:29:12)
    at Object.i [as highlight] (core.js:39:11)
    at G.astGenerator (highlight.js:296:27)
    at M (highlight.js:399:20)
    at si (react-dom.production.min.js:157:137)
    at Ks (react-dom.production.min.js:267:460)
    at Il (react-dom.production.min.js:250:347)
    at Ol (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
cs @ react-dom.production.min.js:216
r.payload @ react-dom.production.min.js:217
da @ react-dom.production.min.js:130
Wi @ react-dom.production.min.js:184
Ks @ react-dom.production.min.js:269
Il @ react-dom.production.min.js:250
Ol @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
bl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Jo @ react-dom.production.min.js:122
Zo @ react-dom.production.min.js:123
Go @ react-dom.production.min.js:122
wl @ react-dom.production.min.js:244
notify @ Subscription.js:19
t.notifyNestedSubs @ Subscription.js:90
t.handleChangeWrapper @ Subscription.js:95
v @ redux.js:296
(anonymous) @ utils.js:180
(anonymous) @ redux.js:546
(anonymous) @ actions.js:250
await in (anonymous) (async)
y @ debounce.js:95
x @ debounce.js:144
E @ debounce.js:132
setTimeout (async)
b @ debounce.js:103
_ @ debounce.js:172
(anonymous) @ actions.js:266
(anonymous) @ utils.js:177
(anonymous) @ redux.js:546
(anonymous) @ OperationContainer.jsx:159
(anonymous) @ OperationContainer.jsx:112
Ve @ react-dom.production.min.js:52
Ge @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
On @ react-dom.production.min.js:100
jn @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Mn @ react-dom.production.min.js:105
Xt @ react-dom.production.min.js:75
Qt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Jo @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Zt @ react-dom.production.min.js:73
error-boundary.jsx:18 
        
       Error: Expected `string` for value, got `true`
    at t (index.js:29:12)
    at Object.i [as highlight] (core.js:39:11)
    at G.astGenerator (highlight.js:296:27)
    at M (highlight.js:399:20)
    at si (react-dom.production.min.js:157:137)
    at Ks (react-dom.production.min.js:267:460)
    at Il (react-dom.production.min.js:250:347)
    at Ol (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163) {componentStack: '\n    at M (http://localhost:4000/documentation/swa…4000/documentation/swagger-ui-bundle.js:2:212284)'}```

**Comment by writch** [comment]
Following up, I have a _workaround_ which is very ugly, but workable.

The annotation:

`// @Param       Quarantine 		body     boolean false "Quarantine room or not"`

fails if the term is 'bool' instead of 'boolean'.  I let it generate the docs.

Then I edit docs/docs.go and modify the term 'boolean' to be 'bool', thus:

`                    {
                        "description": "Quarantine room or not",
                        "name": "Quarantine",
                        "in": "body",
                        "schema": {
                            "type": "bool"
                        }
                    }`

This results in the parameters block being presented w/o error

**Comment by writch** [comment]
This was resolved by having the @Param line explicitly reference the object instead of having multiple lines referencing each one individually.
