### ISSUE TITLE
When I define a Param type with body, panic: assignment to entry in nil map 

### ISSUE THREAD

**Issue by axiaoxin** [swaggo/swag#235]
**Describe the bug**

there is a Label model in models package:

    type Label struct {
    	BaseModel
    	Name    string    `gorm:"type:varchar(32);not null;default:'';unique_index" json:"name" binding:"required,max=32" example:"server:linux"`
    	Remark  string    `gorm:"type:varchar(64);not null;default:''" json:"remark" binding:"max=64" example:"Linux server"`
    	Objects []*Object `gorm:"many2many:labeling;" json:"objects"`
    }

the apidoc:

    // AddLabel godoc
    // @Summary Add a label
    // @Description add a label
    // @Tags label
    // @Accept json
    // @Produce json
    // @Param label body models.Label true "label info"
    // @Router /label [post]
    // @Success 200 {object} apis.Response
    func AddLabel(c *gin.Context) {
    	var body models.Label
    	if err := c.ShouldBind(&body); err != nil {
    		JSON400(c, retcode.InvalidParams, err.Error())
    	}
    	common.AddLabel(body.Name, body.Remark)
    }

when I run the swag init, raise exception:

    panic: assignment to entry in nil map

    goroutine 1 [running]:
    github.com/swaggo/swag.(*Operation).ParseParamComment(0xc0002305a0, 0xc00042e34a, 0x29, 0xc00046e500, 0x7, 0x31)
	/data/playground/go/src/github.com/swaggo/swag/operation.go:154 +0x83b
    github.com/swaggo/swag.(*Operation).ParseComment(0xc0002305a0, 0xc00042e340, 0x33, 0xc00046e500, 0x0, 0x0)
	/data/playground/go/src/github.com/swaggo/swag/operation.go:73 +0x3a9
    github.com/swaggo/swag.(*Parser).ParseRouterAPIInfo(0xc0003f6700, 0xc00046e500)
	/data/playground/go/src/github.com/swaggo/swag/parser.go:311 +0x17e
    github.com/swaggo/swag.(*Parser).ParseAPI(0xc0003f6700, 0x8ddd7d, 0x2, 0x7fff159404e7, 0x7, 0x7fd97c3176c0, 0x0)
	/data/playground/go/src/github.com/swaggo/swag/parser.go:93 +0x22f
    github.com/swaggo/swag/gen.(*Gen).Build(0xc000199998, 0x8ddd7d, 0x2, 0x7fff159404e7, 0x7, 0x8e15f4, 0xe, 0x8dfa26, 0x9, 0x0, ...)
	/data/playground/go/src/github.com/swaggo/swag/gen/gen.go:30 +0x28e
    main.main.func1(0xc0001ba160, 0xc00046e100, 0xc0001ba160)
	/data/playground/go/src/github.com/swaggo/swag/cmd/swag/main.go:33 +0x18a
    github.com/urfave/cli.HandleAction(0x847a20, 0x8fadb8, 0xc0001ba160, 0x0, 0xc0004162a0)
	/data/playground/go/src/github.com/urfave/cli/app.go:501 +0xc8
    github.com/urfave/cli.Command.Run(0x8de3c7, 0x4, 0x0, 0x0, 0xc0003240d0, 0x1, 0x1, 0x8e169c, 0xe, 0x0, ...)
	/data/playground/go/src/github.com/urfave/cli/command.go:165 +0x459
    github.com/urfave/cli.(*App).Run(0xc00019e000, 0xc00001e0c0, 0x4, 0x4, 0x0, 0x0)
	/data/playground/go/src/github.com/urfave/cli/app.go:259 +0x6bb
    main.main()
	/data/playground/go/src/github.com/swaggo/swag/cmd/swag/main.go:61 +0x4a8

**swag version**
v1.4.0

if change the `body` keyword to others, it is working, just body will panic

**Comment by axiaoxin** [comment]
I want to generate the docs directory in subdir, so I run `swag init` in subdir and import docs from subdir, so paniced.

Fixed it by generate the docs in directory of main.go, does init cmd only running at the main.go dir?
