### ISSUE TITLE
Panics after upgrade to `1.6.3` from `1.6.2`

### ISSUE THREAD

**Issue by bradleygore** [swaggo/swag#533]
**Describe the bug**
I get a stack trace with little for me to go on as to why it's failing when running `swag init ...`.  This same exact codebase has no issues when ran with `swag `1.6.2`. Apologies I can't provide more information than the stack trace below, but that is all I get from the command.

```
$ swag init -g ./v1.go -o ./swagger-docs --parseDependency true

2019/10/02 12:31:26 Generate swagger docs....
2019/10/02 12:31:26 Generate general API Info, search dir:./
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1458dc2]

goroutine 1 [running]:
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc000128070, 0xc000ae25d0, 0x0, 0x0)
        /Users/bgore/go/pkg/mod/github.com/swaggo/swag@v1.6.3/parser.go:1323 +0x62
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc000128070, 0xc000ef0420, 0x0, 0x0)
        /Users/bgore/go/pkg/mod/github.com/swaggo/swag@v1.6.3/parser.go:1341 +0x13e
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc000128070, 0xc0000f8f20, 0x0, 0x0)
        /Users/bgore/go/pkg/mod/github.com/swaggo/swag@v1.6.3/parser.go:1341 +0x13e
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc000128070, 0xc000cf1238, 0x0, 0x0)
        /Users/bgore/go/pkg/mod/github.com/swaggo/swag@v1.6.3/parser.go:1341 +0x13e
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc000128070, 0xc0005aecf0, 0x0, 0x0)
        /Users/bgore/go/pkg/mod/github.com/swaggo/swag@v1.6.3/parser.go:1341 +0x13e
github.com/swaggo/swag.(*Parser).ParseAPI(0xc000128070, 0x159a1bc, 0x2, 0x7ffeefbffaf5, 0x7, 0x0, 0x1)
        /Users/bgore/go/pkg/mod/github.com/swaggo/swag@v1.6.3/parser.go:130 +0x438
github.com/swaggo/swag/gen.(*Gen).Build(0xc0014e7656, 0xc0014e76a8, 0x0, 0x0)
        /Users/bgore/go/pkg/mod/github.com/swaggo/swag@v1.6.3/gen/gen.go:66 +0x1a7
main.main.func1(0xc0002c4000, 0x0, 0xc00013a310)
        /Users/bgore/go/pkg/mod/github.com/swaggo/swag@v1.6.3/cmd/swag/main.go:45 +0x2dc
github.com/urfave/cli.HandleAction(0x14ebd60, 0x15bcb88, 0xc0002c4000, 0xc0002c4000, 0x0)
        /Users/bgore/go/pkg/mod/github.com/urfave/cli@v1.21.0/app.go:514 +0xbe
github.com/urfave/cli.Command.Run(0x159a80d, 0x4, 0x0, 0x0, 0xc00032e000, 0x1, 0x1, 0x159de56, 0xe, 0x0, ...)
        /Users/bgore/go/pkg/mod/github.com/urfave/cli@v1.21.0/command.go:171 +0x4cd
github.com/urfave/cli.(*App).Run(0xc0002a4000, 0xc0000c8000, 0x8, 0x8, 0x0, 0x0)
        /Users/bgore/go/pkg/mod/github.com/urfave/cli@v1.21.0/app.go:265 +0x72f
main.main()
        /Users/bgore/go/pkg/mod/github.com/swaggo/swag@v1.6.3/cmd/swag/main.go:93 +0x65d
```

**Expected behavior**
The errors along the way to provide some specific contextual information.

**Your swag version**
e.g. 1.6.3

**Your go version**
e.g. 1.13

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: N/A
 - Version: N/A

**Comment by bradleygore** [comment]
Just for comparison sake, I rolled back to `1.6.2` and this is the output I get:

```
$ swag init -g v1.go -o swagger-docs --parseDependency true
2019/10/02 12:42:10 Generate swagger docs....
2019/10/02 12:42:10 Generate general API Info, search dir:./
2019/10/02 12:42:46 Generating jsonpatch.Patch
2019/10/02 12:42:46 Generating query.Opts
2019/10/02 12:42:46 Generating query.SearchCriterions
2019/10/02 12:42:46 Generating query.SearchCriteria
2019/10/02 12:42:46 Generating typename.TypeName
2019/10/02 12:42:46 Generating query.PagedResults
2019/10/02 12:42:46 Generating types.APIError
2019/10/02 12:42:46 Generating types.APIValidationError
2019/10/02 12:42:46 Generating types.BridgeUser
2019/10/02 12:42:46 Generating types.TimeZone
2019/10/02 12:42:46 Generating types.IDSet
2019/10/02 12:42:46 Generating types.DayPart
2019/10/02 12:42:46 Generating types.DayPartSchedule
2019/10/02 12:42:46 Generating types.HMS24
2019/10/02 12:42:46 Generating types.APIDateRange
2019/10/02 12:42:46 Field type of '*ast.SelectorExpr' is unsupported. Skipping
2019/10/02 12:42:46 Generating types.APIDate
2019/10/02 12:42:46 Field type of '*ast.SelectorExpr' is unsupported. Skipping
2019/10/02 12:42:46 Skipping 'types.APIDate', already parsed.
2019/10/02 12:42:46 Generating types.Employee
2019/10/02 12:42:46 Skipping 'types.IDSet', already parsed.
2019/10/02 12:42:46 Skipping 'types.IDSet', already parsed.
2019/10/02 12:42:46 Generating types.EmploymentPeriod
2019/10/02 12:42:46 Skipping 'types.APIDate', already parsed.
2019/10/02 12:42:46 Skipping 'types.APIDate', already parsed.
2019/10/02 12:42:46 Skipping 'types.IDSet', already parsed.
2019/10/02 12:42:46 Generating types.JobPosition
2019/10/02 12:42:46 Skipping 'types.IDSet', already parsed.
2019/10/02 12:42:46 Generating types.JobPositionCategory
2019/10/02 12:42:46 Generating types.JobPositionAuthTypes
2019/10/02 12:42:46 Generating types.JobRole
2019/10/02 12:42:46 Generating types.Location
2019/10/02 12:42:46 Skipping 'types.TimeZone', already parsed.
2019/10/02 12:42:46 Skipping 'types.IDSet', already parsed.
2019/10/02 12:42:46 Skipping 'types.IDSet', already parsed.
2019/10/02 12:42:46 Generating types.LocationGroup
2019/10/02 12:42:46 Generating types.LocationIntegrationConfig
2019/10/02 12:42:46 Generating types.NewBridgeUser
2019/10/02 12:42:46 Generating types.OrderType
2019/10/02 12:42:46 Generating types.Organization
2019/10/02 12:42:46 Generating types.IntegrationIDs
2019/10/02 12:42:46 Generating currency.IDs
2019/10/02 12:42:46 Skipping 'currency.IDs', already parsed.
2019/10/02 12:42:46 Generating types.POSOperatorAuthNPayload
2019/10/02 12:42:46 Generating types.POSOperatorAuthNResponse
2019/10/02 12:42:46 Skipping 'types.Employee', already parsed.
2019/10/02 12:42:46 Skipping 'types.JobPosition', already parsed.
2019/10/02 12:42:46 Skipping 'types.JobPosition', already parsed.
2019/10/02 12:42:46 Generating types.RevenueCategory
2019/10/02 12:42:46 Generating types.RevenueCenter
2019/10/02 12:42:46 Generating types.SystemUserAuthNResponse
2019/10/02 12:42:46 Skipping 'types.BridgeUser', already parsed.
2019/10/02 12:42:46 Generating types.SystemUserCreds
2019/10/02 12:42:46 Generating types.TaxRate
2019/10/02 12:42:46 Generating currency.PreciseAmount
2019/10/02 12:42:46 Skipping 'currency.PreciseAmount', already parsed.
2019/10/02 12:42:46 Generating types.TaxType
2019/10/02 12:42:46 create docs.go at  swagger-docs/docs.go
2019/10/02 12:42:46 create swagger.json at  swagger-docs/swagger.json
2019/10/02 12:42:46 create swagger.yaml at  swagger-docs/swagger.yaml
```

Notice there are a couple of these `Field type of '*ast.SelectorExpr' is unsupported. Skipping` lines. I don't know specifically what they are for, as I have no `*ast.SelectorExpr` types in use so must be an internal error. I don't know if something was gracefully handled in `1.6.2` that is not gracefully handled in `1.6.3` or what...

**Comment by ubogdan** [comment]
The bug has nothing to do with ast.SelectorExpr , it happing [here]( https://github.com/swaggo/swag/blob/c9f403a30434dc43903a02f80bcf736f11169a86/parser.go#L1323).
@bradleygore thanks for bringing our attention. 
You should try to generate without "--parseDependency" if "types" and "currency" packages are located in the root path of your "$ swag init" execution.

**Comment by bradleygore** [comment]
other packages aren't at the root of that path, so I'm using `--parseDependency` by necessity :)

**Comment by KristaHyer1** [comment]
I have also hit this issue, and downgrading also fixed this for me
