### ISSUE TITLE
panic when swag init with parseDependency=true and depend on "C" library

### ISSUE THREAD

**Issue by brotherbin** [swaggo/swag#674]
**Describe the bug**
panic happened when swag init with parseDependency=true and depend on "C" library
panic code (pkg.Raw is nil when pkg is "C"):

```golang
func (parser *Parser) getAllGoFileInfoFromDeps(pkg *depth.Pkg) error {
	if pkg.Internal || !pkg.Resolved { // ignored internal and not resolved dependencies
		return nil
	}

	srcDir := pkg.Raw.Dir // pkg.Raw is nil when pkg is "C"
        // omit
}
```

**To Reproduce**
1. import "github.com/confluentinc/confluent-kafka-go v1.4.0" (which depend on "C" library)
2. swag init -parseDependency true
3. see a panic

>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x145ed92] 
goroutine 1 [running]:
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc000256b60, 0xc00040aaf8, 0x0, 0x0)
	/Users/dobbin/go/pkg/mod/github.com/swaggo/swag@v1.6.5/parser.go:1414 +0x62
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc000256b60, 0xc0005aa898, 0x0, 0x0)
	/Users/dobbin/go/pkg/mod/github.com/swaggo/swag@v1.6.5/parser.go:1432 +0x13e

**Expected behavior**
do not panic

**Screenshots**
>swag init --generalInfo routers/router.go --parseDependency true
2020/04/13 16:10:18 Generate swagger docs....
2020/04/13 16:10:18 Generate general API Info, search dir:./
2020/04/13 16:10:18 pkg name: gitlab.com/watermirror/pos-kernel/task/routers
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x145ed92]
goroutine 1 [running]:
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc000256b60, 0xc00040aaf8, 0x0, 0x0)
	/Users/dobbin/go/pkg/mod/github.com/swaggo/swag@v1.6.5/parser.go:1414 +0x62
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc000256b60, 0xc0005aa898, 0x0, 0x0)
	/Users/dobbin/go/pkg/mod/github.com/swaggo/swag@v1.6.5/parser.go:1432 +0x13e
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc000256b60, 0xc00064d970, 0x0, 0x0)
	/Users/dobbin/go/pkg/mod/github.com/swaggo/swag@v1.6.5/parser.go:1432 +0x13e
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc000256b60, 0xc00064cdc0, 0x0, 0x0)
	/Users/dobbin/go/pkg/mod/github.com/swaggo/swag@v1.6.5/parser.go:1432 +0x13e
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc000256b60, 0xc0004a9c88, 0x0, 0x0)
	/Users/dobbin/go/pkg/mod/github.com/swaggo/swag@v1.6.5/parser.go:1432 +0x13e
github.com/swaggo/swag.(*Parser).ParseAPI(0xc000256b60, 0x15cbe81, 0x2, 0x7ffeefbffb78, 0x11, 0x0, 0xc0003fd6f0)
	/Users/dobbin/go/pkg/mod/github.com/swaggo/swag@v1.6.5/parser.go:135 +0x485
github.com/swaggo/swag/gen.(*Gen).Build(0xc0002d9930, 0xc0070a37f8, 0x0, 0x0)
	/Users/dobbin/go/pkg/mod/github.com/swaggo/swag@v1.6.5/gen/gen.go:77 +0x1a7
main.initAction(0xc0002042c0, 0x0, 0xc00020c480)
	/Users/dobbin/go/pkg/mod/github.com/swaggo/swag@v1.6.5/cmd/swag/main.go:73 +0x33a
github.com/urfave/cli.HandleAction(0x1519960, 0x15f3880, 0xc0002042c0, 0xc0002042c0, 0x0)
	/Users/dobbin/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0xbe
github.com/urfave/cli.Command.Run(0x15cc82d, 0x4, 0x0, 0x0, 0xc0002d95c0, 0x1, 0x1, 0x15d30db, 0xe, 0x0, ...)
	/Users/dobbin/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x528
github.com/urfave/cli.(*App).Run(0xc000022380, 0xc0000201e0, 0x6, 0x6, 0x0, 0x0)
	/Users/dobbin/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279 +0x731
main.main()
	/Users/dobbin/go/pkg/mod/github.com/swaggo/swag@v1.6.5/cmd/swag/main.go:98 +0x1c4

**Your swag version**
1.6.5

**Your go version**
1.13

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: [e.g. 22]

**Additional context**
panic fixed when I add following code
```golang
func (parser *Parser) getAllGoFileInfoFromDeps(pkg *depth.Pkg) error {
	if pkg.Internal || !pkg.Resolved { // ignored internal and not resolved dependencies
		return nil
	}
        if pkg.Raw == nil {
                 return nil
        }
	srcDir := pkg.Raw.Dir // pkg.Raw is nil when pkg is "C"
        // omit
```

**Comment by brotherbin** [comment]
the following pr may solve the issue
#662
